format = """\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $python\
    $golang\
    $nodejs\
    $rust\
    $package\
    $terraform\
    $cmd_duration\

    $fill\
    $kubernetes\
    $aws\
    $gcloud\
    $line_break\
    $character\
    """

command_timeout = 1000

[aws]
symbol = " "

[cmd_duration]
format = "took [$duration]($style) "

[c]
symbol = " "

[directory]
read_only = " "
truncate_to_repo = false
truncation_length = 3

[docker_context]
symbol = " "

[git_branch]
symbol = " "
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
deleted = "󰆴 "

[gcloud]
symbol = "󱇶  "
format = "[$symbol$active]($style) "

[golang]
symbol = " "
format = "[$symbol($version )]($style)"

[kubernetes]
symbol = "󱃾  "
format = '[$symbol$context( \($namespace\))]($style) '
disabled = false

[lua]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[fill]
symbol = " "
