#!/usr/bin/env sh
# Options: https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc
# Commands: https://github.com/koekeishiya/yabai/wiki/Commands

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_moved action="sketchybar --trigger windows_on_spaces"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_animation_duration    0.0
yabai -m config window_opacity_duration      0.15

yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90

yabai -m config window_border                on
yabai -m config window_border_width          3
yabai -m config window_border_radius         11
yabai -m config window_border_blur           on
yabai -m config window_border_hidpi          off
yabai -m config active_window_border_color   0xfff5a97f
yabai -m config normal_window_border_color   0xff8087a2
yabai -m config insert_feedback_color        0xff61afef

yabai -m config split_ratio                  0.50
yabai -m config split_type                   auto
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

yabai -m config layout                       bsp
yabai -m config top_padding                  56
yabai -m config bottom_padding               8
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   6

yabai -m rule --add app="^システム情報$" manage=off # About This Mac
yabai -m rule --add app="^DeepL$" manage=off
yabai -m rule --add app="^Karabiner-.*$" manage=off

echo "yabai configuration loaded.."
