#!/usr/bin/env sh
# examples: https://github.com/cmacrae/spacebar/blob/master/examples/spacebarrc

spacebar -m config position                    top
spacebar -m config height                      32
spacebar -m config spacing_left                25
spacebar -m config spacing_right               15
spacebar -m config text_font                   "Helvetica Neue:Bold:16.0"
spacebar -m config icon_font                   "Hack Nerd Font Mono:Regular:15.0"
spacebar -m config background_color            0xff1e2127 # 0xff202020
spacebar -m config foreground_color            0xffa8a8a8
spacebar -m config space_icon_color            0xff458588
spacebar -m config power_icon_color            0xffcd950c
spacebar -m config battery_icon_color          0xffd75f5f
spacebar -m config dnd_icon_color              0xffa8a8a8
spacebar -m config clock_icon_color            0xffa8a8a8
spacebar -m config space_icon_strip            1 2 3 4 5 6 7 8 9 10
spacebar -m config space_icon_color            0xffffa500
spacebar -m config space_icon_color_secondary  0xff78c4d4
spacebar -m config space_icon_color_tertiary   0xfffff9b0
spacebar -m config power_icon_strip             
spacebar -m config space_icon                  
spacebar -m config clock_icon                  
spacebar -m config dnd_icon                    
spacebar -m config clock_format                "%y/%m/%d %R"

spacebar -m config right_shell                 off
spacebar -m config right_shell_icon            
spacebar -m config right_shell_command         "whoami"

echo "spacebar configuration loaded.."
